CREATE SEQUENCE orders_seq START WITH 17000000 INCREMENT BY 7;

CREATE TABLE orders (
  id VARCHAR PRIMARY KEY NOT NULL,
  price DOUBLE NOT NULL,  
  vouncher VARCHAR NOT NULL, 
  status INT NOT NULL,  
  creation_date TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL);


CREATE SEQUENCE users_seq START WITH 5000 INCREMENT BY 1;
CREATE TABLE users (
  id INT DEFAULT users_seq.nextval PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  age INT NOT NULL,  
  creation_date TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL);

